### ISSUE TITLE
Release C bindings

### ISSUE THREAD

**Issue by joeroe** [Stranger6667/css-inline#293] opened 2023-12-14 16:54 UTC
#216 added C bindings (#209), but it doesn't look like they were ever released, i.e. there are no GitHub releases with [C] in the title and the "[C] Release" workflow has never been run.

**Comment by Stranger6667** [comment] 2023-12-14 17:43
Hi!

The issue is that I didn't properly think about release automation. Maybe, the way to go would be to create a GH release automatically in that release workflow and attach the generated artifacts to it. Something like https://github.com/softprops/action-gh-release might work + some simple script to extract the release notes from (not-yet-existing) `Changelog.md` for C bindings.

**Comment by Stranger6667** [comment] 2023-12-14 20:11
Here is the release - https://github.com/Stranger6667/css-inline/releases/tag/c-v0.11.3

There are a few things to polish, though, maybe `strip`, at least, but I am going to check it alter.

**Comment by Stranger6667** [comment] 2023-12-28 15:00
As the release is automated now, I am going to close this issue. Feel free to open a new issue should you have any issues with C bindings :)

**Closed by Stranger6667** 2023-12-28 15:00 UTC
