### ISSUE TITLE
Child selector styles not being applied

### ISSUE THREAD

**Issue by caseyjhol** [Stranger6667/css-inline#185] opened 2023-05-16 22:12 UTC
```css
.parent {
  overflow: hidden;
  box-shadow: 0 4px 10px 0px rgba(0, 0, 0, 0.1);
}
.parent > table > tbody > tr > td,
.parent > table > tbody > tr > td > div {
  border-radius: 3px;
}
```

```html
<div class="parent">
    <table>
        <tbody>
            <tr>
                <td>
                    <div>
                        Test
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
```

Actual:
```html
<div class="parent" style="overflow: hidden; box-shadow: 0 4px 10px 0px rgba(0, 0, 0, 0.1);">
    <table>
        <tbody>
            <tr>
                <td>
                    <div>
                        Test
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
```

Expected:
```html
<div class="parent" style="overflow: hidden; box-shadow: 0 4px 10px 0px rgba(0, 0, 0, 0.1);">
    <table>
        <tbody>
            <tr>
                <td style="border-radius: 3px;">
                    <div style="border-radius: 3px;">
                        Test
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
```

**Comment by Stranger6667** [comment] 2023-05-30 05:13
Hi! Sorry for the delay

That is strange, the code below works with the latest `css-inline` crate version:

```rust
fn main() {
    let html = r#"<html>
   <head>
      <title>Test</title>
      <style>.parent {
         overflow: hidden;
         box-shadow: 0 4px 10px 0px rgba(0, 0, 0, 0.1);
         }
         .parent > table > tbody > tr > td,
         .parent > table > tbody > tr > td > div {
         border-radius: 3px;
         }
      </style>
   </head>
   <body>
      <div class="parent">
         <table>
            <tbody>
               <tr>
                  <td>
                     <div>
                        Test
                     </div>
                  </td>
               </tr>
            </tbody>
         </table>
      </div>
   </body>
</html>"#;
    let inlined = css_inline::inline(&html).unwrap();
    assert_eq!(
        inlined,
        r#"<html><head><title>Test</title><style>.parent {
  overflow: hidden;
  box-shadow: 0 4px 10px 0px rgba(0, 0, 0, 0.1);
}
.parent > table > tbody > tr > td,
.parent > table > tbody > tr > td > div {
  border-radius: 3px;
}</style></head><body><div class="parent" style="overflow: hidden;box-shadow: 0 4px 10px 0px rgba(0, 0, 0, 0.1);">
    <table>
        <tbody>
            <tr>
                <td style="border-radius: 3px;">
                    <div style="border-radius: 3px;">
                        Test
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div></body></html>"#
    );
}
```

which seems to be matching with the provided example (+ html/head/body tags)

What version do you use? any code snippets would be helpful

**Comment by Stranger6667** [comment] 2023-06-10 16:45
I'm going to close this one because I can't reproduce the problem, but the provided reproducer inlines CSS as expected. Please feel free to re-open the issue in case there is more info to dig into.

**Closed by Stranger6667** 2023-06-10 16:45 UTC
Labels: Type: Bug

**Comment by caseyjhol** [comment] 2023-06-10 17:51
Sorry - been busy with another project. Will update ASAP. I'm using the Python crate FWIW.

**Comment by caseyjhol** [comment] 2023-09-21 17:35
To close the loop here, I figured out what the issue was. My CSS was getting escaped before passing into css-inline. As a result, `>` became `&gt;`, and those selectors were then getting ignored. So, definitely an issue on my end. Apologies for misreporting and thanks for checking into this for me.

**Comment by Stranger6667** [comment] 2023-09-21 18:09
Thank you for confirmation!
